# Generated by Django 5.1.1 on 2025-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_day_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Этот номер телефона уже зарегистрирован'}, max_length=20, null=True, unique=True),
        ),
    ]
