# Generated by Django 5.1.1 on 2025-04-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carscategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
